package SevenWonders.GameLogic.Enums;

public enum GOD_POWER_TYPE {
    EXTRA_WAR_TOKENS,
    SCIENTIFIC_REGRESSION,
    VP_EACH_TURN,
    EARTHQUAKE,
    BLOCK_AND_DESTROY_CARD,
    FORESIGHT,
    ECONOMIC_DEPRESSION
}
