package SevenWonders.GameLogic.Enums;

public enum WONDER_TYPE {
    GREAT_PYRAMID_OF_GIZA,
    HANGING_GARDENS,
    STATUE_OF_ZEUS,
    TEMPLE_OF_ARTEMIS,
    MAUSOLEUM_AT_HALICARNASSUS,
    COLOSSUS_OF_RHODES,
    LIGHTHOUSE_OF_ALEXANDRIA
}
